// ─── Demo Mode Mock Data ──────────────────────────────────────────────────────
// All API responses used when running in demo mode (GitHub Pages / no backend)

export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'm.alharbi@privora.demo',
  name: 'M. Alharbi',
  phone: '+966 50 123 4567',
  role: 'user' as const,
  isEmailVerified: true,
  preferredLanguage: 'en' as const,
};

export const DEMO_ADMIN = {
  id: 'demo-admin-001',
  email: 'b.alanazi@privora.demo',
  name: 'B. Alanazi',
  role: 'org_admin' as const,
  organizationId: 'org-001',
  organization: { id: 'org-001', name: 'Ministry of Health' },
  isEmailVerified: true,
  preferredLanguage: 'en' as const,
};

export const DEMO_TOKENS = {
  accessToken: 'demo-access-token',
  refreshToken: 'demo-refresh-token',
};

// ─── Consent Requests (pending for user) ──────────────────────────────────────
export const DEMO_CONSENT_REQUESTS = [
  {
    id: 'req-001',
    title: 'Health Records Access',
    titleAr: 'الوصول إلى السجلات الصحية',
    description: 'We need access to your health records to provide you with personalized healthcare recommendations and improve our diagnostic services.',
    dataTypes: ['health_data', 'contact_info'],
    purpose: 'Medical diagnosis and treatment planning',
    legalBasis: 'legitimate_interest',
    retentionPeriod: '5 years',
    isActive: true,
    organization: { id: 'org-001', name: 'Ministry of Health' },
    privacyPolicyUrl: 'https://moh.gov.sa/privacy',
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-002',
    title: 'Financial Data for Credit Scoring',
    titleAr: 'البيانات المالية لتقييم الائتمان',
    description: 'Aramco Financial Services requires access to your financial history to assess credit eligibility and offer tailored loan products.',
    dataTypes: ['financial_data', 'identity_data'],
    purpose: 'Credit risk assessment',
    legalBasis: 'contractual_necessity',
    retentionPeriod: '7 years',
    isActive: true,
    organization: { id: 'org-002', name: 'Aramco Financial Services' },
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-003',
    title: 'Location Data for Delivery Services',
    description: 'We collect your location data to optimize delivery routes and provide accurate ETAs for your orders.',
    dataTypes: ['location_data'],
    purpose: 'Logistics optimization and delivery tracking',
    legalBasis: 'consent',
    retentionPeriod: '1 year',
    isActive: true,
    organization: { id: 'org-003', name: 'NEOM Smart Logistics' },
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Consent History ───────────────────────────────────────────────────────────
export const DEMO_CONSENT_HISTORY = [
  {
    id: 'hist-001',
    status: 'approved',
    reason: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    consentRequest: {
      id: 'req-old-001',
      title: 'Marketing Communications',
      organization: { name: 'STC Pay' },
    },
  },
  {
    id: 'hist-002',
    status: 'rejected',
    reason: 'Not comfortable sharing this data',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    consentRequest: {
      id: 'req-old-002',
      title: 'Behavioral Analytics',
      organization: { name: 'Jarir Bookstore' },
    },
  },
  {
    id: 'hist-003',
    status: 'approved',
    reason: null,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    consentRequest: {
      id: 'req-old-003',
      title: 'Identity Verification',
      organization: { name: 'Absher Platform' },
    },
  },
  {
    id: 'hist-004',
    status: 'withdrawn',
    reason: 'Changed my mind',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    consentRequest: {
      id: 'req-old-004',
      title: 'Shopping Preferences',
      organization: { name: 'Amazon.sa' },
    },
  },
  {
    id: 'hist-005',
    status: 'approved',
    reason: null,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    consentRequest: {
      id: 'req-old-005',
      title: 'Health Insurance Processing',
      organization: { name: 'Tawuniya Insurance' },
    },
  },
];

// ─── Org Consent Requests ─────────────────────────────────────────────────────
export const DEMO_ORG_REQUESTS = [
  {
    id: 'req-001',
    title: 'Health Records Access',
    purpose: 'Medical diagnosis and treatment planning',
    dataTypes: ['health_data', 'contact_info'],
    legalBasis: 'legitimate_interest',
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    _count: { transactions: 142 },
  },
  {
    id: 'req-004',
    title: 'Patient Feedback Survey',
    purpose: 'Service quality improvement',
    dataTypes: ['contact_info', 'behavioral_data'],
    legalBasis: 'consent',
    isActive: true,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    _count: { transactions: 89 },
  },
  {
    id: 'req-005',
    title: 'Telemedicine Data Processing',
    purpose: 'Remote consultation services',
    dataTypes: ['health_data', 'biometric_data', 'contact_info'],
    legalBasis: 'contractual_necessity',
    isActive: false,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    _count: { transactions: 210 },
  },
];

// ─── Analytics ────────────────────────────────────────────────────────────────
const buildDailyTrend = () => {
  const rows: { date: string; status: string; count: string }[] = [];
  // statuses: approved, rejected, withdrawn
  for (let i = 29; i >= 0; i--) {
    const d = new Date(Date.now() - i * 24 * 60 * 60 * 1000);
    const date = d.toISOString().split('T')[0];
    rows.push({ date, status: 'approved', count: String(Math.floor(Math.random() * 20) + 5) });
    rows.push({ date, status: 'rejected', count: String(Math.floor(Math.random() * 8) + 1) });
    if (i % 4 === 0) rows.push({ date, status: 'withdrawn', count: String(Math.floor(Math.random() * 3) + 1) });
  }
  return rows;
};

export const DEMO_ANALYTICS = {
  summary: {
    totalRequests: 3,
    activeRequests: 2,
    totalResponses: 441,
    uniqueRespondents: 312,
    approvalRate: 71.2,
  },
  statusBreakdown: { approved: 314, rejected: 98, withdrawn: 29, pending: 0 },
  topRequests: [
    { id: 'req-001', title: 'Health Records Access', total_responses: 142, approved: 102, rejected: 32, withdrawn: 8 },
    { id: 'req-004', title: 'Patient Feedback Survey', total_responses: 89, approved: 71, rejected: 14, withdrawn: 4 },
    { id: 'req-005', title: 'Telemedicine Data Processing', total_responses: 210, approved: 141, rejected: 52, withdrawn: 17 },
  ],
  dailyTrend: buildDailyTrend(),
};

// ─── Data Sharing Requests (user view — incoming from orgs) ───────────────────
export const DEMO_USER_DATA_SHARING_REQUESTS = [
  {
    id: 'dsr-001',
    title: 'Identity Verification for Loan Application',
    purpose: 'Verify customer identity for credit eligibility assessment',
    purposeCategory: 'identity_verification',
    dataTypes: ['name', 'national_id', 'date_of_birth'],
    duration: '30 days',
    legalBasis: 'consent',
    privacyNotice:
      'Your name, national ID, and date of birth will be accessed solely to verify your identity for the loan application. This data will not be shared with any third party and will be deleted after the verification is complete.',
    status: 'pending_consent',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    requestingOrg: { id: 'org-002', name: 'Aramco Financial Services' },
  },
  {
    id: 'dsr-002',
    title: 'Health Records for Insurance Policy',
    purpose: 'Assess health risk for insurance underwriting',
    purposeCategory: 'insurance',
    dataTypes: ['name', 'health_data', 'date_of_birth'],
    duration: '90 days',
    legalBasis: 'consent',
    privacyNotice:
      'Health information will be used exclusively to determine insurance eligibility and pricing. Data will be stored securely and deleted upon policy decision.',
    status: 'pending_consent',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    requestingOrg: { id: 'org-004', name: 'Tawuniya Insurance' },
  },
  {
    id: 'dsr-003',
    title: 'Employment Background Check',
    purpose: 'Verify employment history for hiring process',
    purposeCategory: 'employment',
    dataTypes: ['name', 'email', 'employment_data'],
    duration: '14 days',
    legalBasis: 'consent',
    status: 'consent_approved',
    respondedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    requestingOrg: { id: 'org-003', name: 'NEOM Smart Logistics' },
  },
  {
    id: 'dsr-004',
    title: 'Government Services Eligibility Check',
    purpose: 'Verify residency status for government benefit eligibility',
    purposeCategory: 'government_service',
    dataTypes: ['name', 'national_id', 'address'],
    duration: '7 days',
    legalBasis: 'legal_obligation',
    status: 'completed',
    respondedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    requestingOrg: { id: 'org-001', name: 'Ministry of Health' },
  },
  {
    id: 'dsr-005',
    title: 'Fraud Prevention Data Check',
    purpose: 'Cross-verify identity to prevent fraudulent transactions',
    purposeCategory: 'fraud_prevention',
    dataTypes: ['name', 'phone', 'national_id'],
    duration: '24 hours',
    legalBasis: 'legitimate_interests',
    status: 'rejected',
    respondedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    requestingOrg: { id: 'org-005', name: 'STC Pay' },
  },
];

// ─── Data Sharing Requests (org view — outgoing) ───────────────────────────────
export const DEMO_ORG_DATA_SHARING_REQUESTS = [
  {
    id: 'dsr-org-001',
    title: 'Patient Identity Cross-Verification',
    purpose: 'Verify patient identity across hospital systems',
    purposeCategory: 'healthcare',
    dataTypes: ['name', 'national_id', 'date_of_birth'],
    duration: '7 days',
    legalBasis: 'legal_obligation',
    status: 'completed',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    respondedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    dataSubject: { id: 'user-001', name: 'Sara Al-Rashidi', email: 'sara@example.com' },
    providingOrg: null,
  },
  {
    id: 'dsr-org-002',
    title: 'Contact Details for Telemedicine Follow-up',
    purpose: 'Send appointment reminders and health reports',
    purposeCategory: 'healthcare',
    dataTypes: ['name', 'email', 'phone'],
    duration: '30 days',
    legalBasis: 'consent',
    status: 'consent_approved',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    respondedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dataSubject: { id: 'user-002', name: 'Khalid Al-Otaibi', email: 'khalid@example.com' },
    providingOrg: null,
  },
  {
    id: 'dsr-org-003',
    title: 'Insurance Pre-Authorization Check',
    purpose: 'Verify insurance coverage before medical procedure',
    purposeCategory: 'insurance',
    dataTypes: ['name', 'national_id'],
    duration: '48 hours',
    legalBasis: 'consent',
    status: 'pending_consent',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    dataSubject: { id: 'user-003', name: 'Fatimah Al-Zahrani', email: 'fatimah@example.com' },
    providingOrg: { id: 'org-004', name: 'Tawuniya Insurance' },
  },
  {
    id: 'dsr-org-004',
    title: 'Emergency Contact Verification',
    purpose: 'Cross-verify next-of-kin contact details',
    purposeCategory: 'healthcare',
    dataTypes: ['name', 'phone'],
    duration: '24 hours',
    legalBasis: 'vital_interests',
    status: 'rejected',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    respondedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    dataSubject: { id: 'user-004', name: 'Omar Al-Ghamdi', email: 'omar@example.com' },
    providingOrg: null,
  },
];

// ─── Data Sharing Transactions (org audit trail) ───────────────────────────────
export const DEMO_DATA_SHARING_TRANSACTIONS = [
  {
    id: 'tx-001',
    dataSharingRequestId: 'dsr-org-001',
    dataTypesShared: ['name', 'national_id', 'date_of_birth'],
    purpose: 'Verify patient identity across hospital systems',
    dataHash: 'a3f5c8e2b1d6f4a79c2e5d8b3f1a6c9e2b5d7f4a1c8e3b6d9f2a5c8e1b4d7f0',
    sharedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    request: { id: 'dsr-org-001', title: 'Patient Identity Cross-Verification', purpose: 'Verify patient identity across hospital systems' },
    dataSubject: { id: 'user-001', name: 'Sara Al-Rashidi', email: 'sara@example.com' },
  },
];

// ─── DSAR Requests (user view) ────────────────────────────────────────────────
export const DEMO_USER_DSAR_REQUESTS = [
  {
    id: 'dsar-001',
    organizationId: 'org-001',
    requestType: 'access',
    description: 'I would like to receive a copy of all personal data you hold about me.',
    status: 'in_progress',
    slaDeadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    daysRemaining: 18,
    isOverdue: false,
    adminNotes: 'We are compiling your data export. You will be notified once ready.',
    responseData: null,
    rejectionReason: null,
    processedAt: null,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    organization: { id: 'org-001', name: 'Ministry of Health' },
  },
  {
    id: 'dsar-002',
    organizationId: 'org-002',
    requestType: 'deletion',
    description: 'Please delete all my personal data as I am no longer a customer.',
    status: 'pending',
    slaDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    daysRemaining: 25,
    isOverdue: false,
    adminNotes: null,
    responseData: null,
    rejectionReason: null,
    processedAt: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    organization: { id: 'org-002', name: 'Aramco Financial Services' },
  },
  {
    id: 'dsar-003',
    organizationId: 'org-004',
    requestType: 'portability',
    description: null,
    status: 'completed',
    slaDeadline: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    daysRemaining: null,
    isOverdue: false,
    adminNotes: 'Data export completed.',
    responseData: 'Your data export has been prepared and sent to your registered email in JSON format.',
    rejectionReason: null,
    processedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    organization: { id: 'org-004', name: 'Tawuniya Insurance' },
  },
];

// ─── DSAR Requests (org/admin view) ──────────────────────────────────────────
export const DEMO_ADMIN_DSAR_REQUESTS = [
  {
    id: 'dsar-a-001',
    requestType: 'access',
    description: 'I would like to receive a copy of all my health records.',
    status: 'in_progress',
    slaDeadline: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    daysRemaining: 8,
    isOverdue: false,
    adminNotes: 'Compiling patient records from three departments.',
    responseData: null,
    rejectionReason: null,
    processedAt: null,
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    dataSubject: { id: 'user-001', name: 'Sara Al-Rashidi', email: 'sara@example.com' },
    processor: { id: 'demo-admin-001', name: 'Mohammed Alharbi' },
  },
  {
    id: 'dsar-a-002',
    requestType: 'deletion',
    description: null,
    status: 'pending',
    slaDeadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
    daysRemaining: 22,
    isOverdue: false,
    adminNotes: null,
    responseData: null,
    rejectionReason: null,
    processedAt: null,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    dataSubject: { id: 'user-002', name: 'Khalid Al-Otaibi', email: 'khalid@example.com' },
    processor: null,
  },
  {
    id: 'dsar-a-003',
    requestType: 'correction',
    description: 'My date of birth is incorrect in your system. It should be 1990-03-15.',
    status: 'completed',
    slaDeadline: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    daysRemaining: null,
    isOverdue: false,
    adminNotes: 'Record corrected in EMR system.',
    responseData: 'Your date of birth has been corrected to 1990-03-15 across all our systems.',
    rejectionReason: null,
    processedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    dataSubject: { id: 'user-003', name: 'Fatimah Al-Zahrani', email: 'fatimah@example.com' },
    processor: { id: 'demo-admin-001', name: 'Mohammed Alharbi' },
  },
  {
    id: 'dsar-a-004',
    requestType: 'objection',
    description: 'I object to my data being used for research purposes.',
    status: 'pending',
    slaDeadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    daysRemaining: 3,
    isOverdue: false,
    adminNotes: null,
    responseData: null,
    rejectionReason: null,
    processedAt: null,
    createdAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
    dataSubject: { id: 'user-004', name: 'Omar Al-Ghamdi', email: 'omar@example.com' },
    processor: null,
  },
];

// ─── Breach Incidents ─────────────────────────────────────────────────────────
export const DEMO_BREACH_INCIDENTS = [
  {
    id: 'breach-001',
    title: 'Patient Portal Unauthorized Access',
    description: 'An unauthorized third party gained read access to the patient portal via a compromised service account. Approximately 1,200 patient records were potentially exposed.',
    breachType: 'unauthorized_access',
    severity: 'high',
    status: 'investigating',
    affectedDataTypes: ['names', 'dates_of_birth', 'health_data', 'contact_info'],
    estimatedAffectedUsers: 1200,
    discoveredAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null,
    actionsTaken: 'Service account disabled. Forensic investigation initiated. IT security team engaged.',
    timeline: [
      {
        timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
        action: 'Incident reported',
        performedBy: 'demo-admin-001',
        note: 'unauthorized_access incident logged by Mohammed Alharbi',
      },
      {
        timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        action: 'Compromised service account isolated',
        performedBy: 'demo-admin-001',
      },
      {
        timestamp: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
        action: 'Forensic investigation initiated with IT security team',
        performedBy: 'demo-admin-001',
      },
    ],
    notifiedAuthority: false,
    notifiedAuthorityAt: null,
    notifiedUsers: false,
    notifiedUsersAt: null,
    authorityDeadline: new Date(new Date(Date.now() - 20 * 60 * 60 * 1000).getTime() + 72 * 60 * 60 * 1000).toISOString(),
    isAuthorityOverdue: false,
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    reporter: { id: 'demo-admin-001', name: 'Mohammed Alharbi', email: 'admin@privora.demo' },
  },
  {
    id: 'breach-002',
    title: 'Staff Laptop Data Loss',
    description: 'A staff member reported losing a work laptop containing unencrypted patient appointment records for the past 3 months.',
    breachType: 'data_loss',
    severity: 'medium',
    status: 'contained',
    affectedDataTypes: ['names', 'appointment_dates', 'contact_info'],
    estimatedAffectedUsers: 340,
    discoveredAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null,
    actionsTaken: 'Remote wipe initiated. SDAIA notified at 47 hours. Affected patients notified by letter.',
    timeline: [
      {
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'Incident reported',
        performedBy: 'demo-admin-001',
        note: 'data_loss incident logged by Mohammed Alharbi',
      },
      {
        timestamp: new Date(Date.now() - 4.5 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'Remote wipe command sent to lost device',
        performedBy: 'demo-admin-001',
      },
      {
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'SDAIA notified within 72h window',
        performedBy: 'demo-admin-001',
      },
    ],
    notifiedAuthority: true,
    notifiedAuthorityAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    notifiedUsers: true,
    notifiedUsersAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    authorityDeadline: new Date(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).getTime() + 72 * 60 * 60 * 1000).toISOString(),
    isAuthorityOverdue: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    reporter: { id: 'demo-admin-001', name: 'Mohammed Alharbi', email: 'admin@privora.demo' },
  },
  {
    id: 'breach-003',
    title: 'Accidental Email Disclosure',
    description: 'A patient\'s medical report was accidentally emailed to the wrong recipient due to an autocomplete error.',
    breachType: 'accidental_disclosure',
    severity: 'low',
    status: 'resolved',
    affectedDataTypes: ['health_data', 'contact_info'],
    estimatedAffectedUsers: 1,
    discoveredAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    actionsTaken: 'Recipient confirmed deletion of email. Patient notified and apologized. Email policy updated.',
    timeline: [
      {
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'Incident reported',
        performedBy: 'demo-admin-001',
        note: 'accidental_disclosure incident logged by Mohammed Alharbi',
      },
      {
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'Recipient contacted and confirmed email deletion',
        performedBy: 'demo-admin-001',
      },
      {
        timestamp: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'Incident resolved — email policy updated',
        performedBy: 'demo-admin-001',
      },
    ],
    notifiedAuthority: true,
    notifiedAuthorityAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    notifiedUsers: true,
    notifiedUsersAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    authorityDeadline: new Date(new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).getTime() + 72 * 60 * 60 * 1000).toISOString(),
    isAuthorityOverdue: false,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    reporter: { id: 'demo-admin-001', name: 'Mohammed Alharbi', email: 'admin@privora.demo' },
  },
];

// ─── Retention Policies ──────────────────────────────────────────────────────
export const DEMO_RETENTION_POLICIES = [
  {
    id: 'ret-001',
    organizationId: 'org-001',
    name: 'Health Data Retention',
    dataCategory: 'sensitive',
    purpose: 'Medical diagnosis and treatment planning',
    retentionDays: 1825,
    retentionYears: 5,
    warningDays: 60,
    action: 'delete',
    isActive: true,
    lastRunAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ret-002',
    organizationId: 'org-001',
    name: 'Patient PII Policy',
    dataCategory: 'pii',
    purpose: 'Patient registration and contact',
    retentionDays: 2555,
    retentionYears: 7,
    warningDays: 30,
    action: 'anonymize',
    isActive: true,
    lastRunAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ret-003',
    organizationId: 'org-001',
    name: 'Financial Records',
    dataCategory: 'financial',
    purpose: 'Billing and insurance claims',
    retentionDays: 3650,
    retentionYears: 10,
    warningDays: 90,
    action: 'alert_only',
    isActive: false,
    lastRunAt: null,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Privacy Notices ──────────────────────────────────────────────────────────
export const DEMO_PRIVACY_NOTICES = [
  {
    id: 'pn-001',
    organizationId: 'org-001',
    title: 'Ministry of Health Privacy Notice',
    version: '1.0',
    purposeOfProcessing: 'To provide healthcare services and manage patient records in compliance with PDPL.',
    dataTypesCollected: ['name', 'date_of_birth', 'health_data', 'contact_info', 'national_id'],
    retentionSummary: '5 years from last appointment date',
    thirdPartySharing: false,
    contactEmail: 'privacy@moh.gov.sa',
    legalBasis: 'legal_obligation',
    dataSubjectRights: ['access', 'correction', 'deletion', 'portability', 'objection'],
    effectiveDate: '2024-01-01',
    changeNotes: null,
    isActive: false,
    previousVersionId: null,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pn-002',
    organizationId: 'org-001',
    title: 'Ministry of Health Privacy Notice',
    version: '2.0',
    purposeOfProcessing: 'To provide comprehensive healthcare services, manage patient records, and facilitate telehealth consultations in compliance with PDPL.',
    dataTypesCollected: ['name', 'date_of_birth', 'health_data', 'contact_info', 'national_id', 'biometric_data'],
    retentionSummary: '7 years from last appointment date per new MOH guidelines',
    thirdPartySharing: true,
    contactEmail: 'dpo@moh.gov.sa',
    legalBasis: 'legal_obligation',
    dataSubjectRights: ['access', 'correction', 'deletion', 'portability', 'objection', 'restrict_processing'],
    effectiveDate: '2025-01-01',
    changeNotes: 'Added telehealth scope, biometric data collection, updated retention to 7 years, added third-party lab sharing disclosure.',
    isActive: true,
    previousVersionId: 'pn-001',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Processing Purposes ──────────────────────────────────────────────────────
export const DEMO_PURPOSES = [
  {
    id: 'purp-001',
    organizationId: 'org-001',
    name: 'Medical Diagnosis',
    description: 'Processing health data to support clinical diagnosis and treatment planning.',
    legalBasis: 'legal_obligation',
    dataCategories: ['pii', 'sensitive'],
    allowedDataTypes: ['name', 'date_of_birth', 'health_data', 'contact_info'],
    requiresExplicitConsent: true,
    retentionDays: 1825,
    isActive: true,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'purp-002',
    organizationId: 'org-001',
    name: 'Patient Communication',
    description: 'Sending appointment reminders, test results, and health advisories.',
    legalBasis: 'contract',
    dataCategories: ['pii'],
    allowedDataTypes: ['name', 'contact_info', 'email'],
    requiresExplicitConsent: false,
    retentionDays: 365,
    isActive: true,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'purp-003',
    organizationId: 'org-001',
    name: 'Biometric Identity Verification',
    description: 'Verifying patient identity using facial recognition and fingerprint at check-in.',
    legalBasis: 'consent',
    dataCategories: ['biometric', 'pii'],
    allowedDataTypes: ['name', 'national_id', 'facial_data', 'fingerprint'],
    requiresExplicitConsent: true,
    retentionDays: 730,
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── RoPA Records ────────────────────────────────────────────────────────────
export const DEMO_ROPA_RECORDS = [
  {
    id: 'ropa-001',
    organizationId: 'org-001',
    activityName: 'Patient Health Records Management',
    activityDescription: 'Collection, storage, and processing of patient health records for clinical treatment purposes.',
    department: 'Clinical Services',
    processingPurpose: 'Medical diagnosis and treatment planning for registered patients',
    legalBasis: 'legal_obligation',
    dataCategories: ['name', 'date_of_birth', 'health_data', 'national_id', 'contact_info'],
    isSensitiveData: true,
    dataSubjectCategories: ['patients', 'outpatients'],
    estimatedDataSubjects: 45000,
    recipientCategories: ['treating physicians', 'laboratory services'],
    thirdPartyTransfers: true,
    crossBorderTransfers: false,
    retentionPeriod: '10 years from last appointment',
    securityMeasures: 'Role-based access, AES-256 encryption at rest, TLS in transit, audit logging',
    dpiaRequired: true,
    dpiaId: 'dpia-001',
    status: 'active',
    ownerRole: 'dpo',
    ownerName: 'Mohammed Alharbi',
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ropa-002',
    organizationId: 'org-001',
    activityName: 'Staff HR Data Processing',
    activityDescription: 'Processing of employee personal data for payroll, benefits, and HR management.',
    department: 'Human Resources',
    processingPurpose: 'Employment contract management, payroll processing, and benefits administration',
    legalBasis: 'contract',
    dataCategories: ['name', 'national_id', 'bank_details', 'contact_info', 'biometric_data'],
    isSensitiveData: true,
    dataSubjectCategories: ['employees', 'contractors'],
    estimatedDataSubjects: 1200,
    recipientCategories: ['payroll provider', 'GOSI', 'HRDF'],
    thirdPartyTransfers: true,
    crossBorderTransfers: false,
    retentionPeriod: '7 years after employment end',
    securityMeasures: 'HR system access controls, encrypted payroll data, segregated network',
    dpiaRequired: false,
    status: 'active',
    ownerRole: 'org_admin',
    ownerName: 'Fatimah Al-Zahrani',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ropa-003',
    organizationId: 'org-001',
    activityName: 'Telemedicine Platform Data',
    activityDescription: 'Processing of patient data for remote consultation services via telemedicine platform.',
    department: 'Digital Health',
    processingPurpose: 'Remote medical consultation and patient monitoring via video and messaging',
    legalBasis: 'consent',
    dataCategories: ['name', 'health_data', 'contact_info', 'location_data'],
    isSensitiveData: true,
    dataSubjectCategories: ['patients', 'remote_patients'],
    estimatedDataSubjects: 8500,
    recipientCategories: ['telemedicine platform provider'],
    thirdPartyTransfers: true,
    crossBorderTransfers: true,
    transferSafeguards: 'Standard contractual clauses with EU-based provider, data residency in KSA',
    retentionPeriod: '5 years from last session',
    securityMeasures: 'End-to-end encrypted video, HIPAA-compliant vendor, penetration testing quarterly',
    dpiaRequired: true,
    status: 'under_review',
    ownerRole: 'dpo',
    ownerName: 'Mohammed Alharbi',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ropa-004',
    organizationId: 'org-001',
    activityName: 'Patient Portal Registration',
    activityDescription: 'Collection of basic registration data for the patient self-service portal.',
    department: 'IT Department',
    processingPurpose: 'Authentication and access management for patient portal',
    legalBasis: 'consent',
    dataCategories: ['name', 'email', 'phone', 'national_id'],
    isSensitiveData: false,
    dataSubjectCategories: ['patients'],
    estimatedDataSubjects: 32000,
    recipientCategories: [],
    thirdPartyTransfers: false,
    crossBorderTransfers: false,
    retentionPeriod: '3 years after account closure',
    securityMeasures: 'MFA, password hashing, session timeouts',
    dpiaRequired: false,
    status: 'draft',
    ownerRole: 'it_admin',
    ownerName: 'Khalid Al-Otaibi',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── DPIA Assessments ─────────────────────────────────────────────────────────
export const DEMO_DPIA_ASSESSMENTS = [
  {
    id: 'dpia-001',
    organizationId: 'org-001',
    title: 'DPIA for Patient Health Records System',
    description: 'Assessment of risks for centralized electronic health records processing at scale across all departments.',
    ropaRecordId: 'ropa-001',
    triggerReason: 'sensitive_data',
    necessityAssessment: 'Processing is strictly necessary for delivery of healthcare services. Health records are required for accurate diagnosis and continuity of care across departments.',
    proportionalityAssessment: 'Data collected is limited to what is clinically necessary. No data is shared beyond treating team without explicit consent.',
    risksIdentified: [
      { risk: 'Unauthorized access to sensitive health records', likelihood: 'medium', impact: 'critical', rating: 'high' },
      { risk: 'Data breach via compromised staff credentials', likelihood: 'medium', impact: 'high', rating: 'high' },
      { risk: 'Third-party lab integration creating data exposure', likelihood: 'low', impact: 'medium', rating: 'low' },
    ],
    mitigationMeasures: [
      { measure: 'Implement MFA for all clinical staff', owner: 'IT Security', targetDate: '2025-03-01', status: 'completed' },
      { measure: 'Annual security awareness training', owner: 'HR', targetDate: '2025-06-01', status: 'in_progress' },
      { measure: 'Quarterly penetration testing', owner: 'IT Security', targetDate: '2025-04-01', status: 'planned' },
    ],
    overallRiskLevel: 'high',
    residualRiskLevel: 'medium',
    dpoConsultationRequired: true,
    dpoConsultationDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    dpoRecommendation: 'Approved with conditions. MFA implementation must be completed before new data integrations proceed.',
    dpoApproved: true,
    status: 'approved',
    approvedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    reviewDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dpia-002',
    organizationId: 'org-001',
    title: 'DPIA for Biometric Staff Check-In System',
    description: 'Impact assessment for fingerprint-based employee attendance system at all hospital entrances.',
    triggerReason: 'sensitive_data',
    necessityAssessment: 'Biometric check-in reduces buddy-punching and improves safety auditing. However, proportionality must be assessed.',
    proportionalityAssessment: 'Biometric data is more privacy-invasive than alternatives. RFID card access may achieve same result with lower risk.',
    risksIdentified: [
      { risk: 'Biometric data breach — irreversible privacy harm', likelihood: 'low', impact: 'critical', rating: 'high' },
      { risk: 'Mission creep — using data beyond attendance tracking', likelihood: 'medium', impact: 'high', rating: 'high' },
    ],
    mitigationMeasures: [
      { measure: 'Store only hashed biometric templates, never raw data', owner: 'IT', targetDate: '2025-05-01', status: 'planned' },
      { measure: 'Strict purpose limitation policy', owner: 'DPO', targetDate: '2025-04-01', status: 'in_progress' },
    ],
    overallRiskLevel: 'high',
    residualRiskLevel: 'medium',
    dpoConsultationRequired: true,
    dpoApproved: null,
    status: 'in_review',
    reviewDate: null,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dpia-003',
    organizationId: 'org-001',
    title: 'DPIA for Telemedicine Cross-Border Data Transfer',
    description: 'Assessment for processing and transferring patient data to telemedicine platform provider.',
    ropaRecordId: 'ropa-003',
    triggerReason: 'cross_border_transfer',
    necessityAssessment: null,
    proportionalityAssessment: null,
    risksIdentified: [],
    mitigationMeasures: [],
    overallRiskLevel: null,
    residualRiskLevel: null,
    dpoConsultationRequired: false,
    dpoApproved: null,
    status: 'draft',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Sensitive Data Records ───────────────────────────────────────────────────
export const DEMO_SENSITIVE_DATA_RECORDS = [
  {
    id: 'sdr-001',
    organizationId: 'org-001',
    dataType: 'health',
    dataTypeDescription: 'Patient medical histories, diagnoses, prescriptions, lab results, and clinical notes',
    processingPurpose: 'Provide clinical treatment, diagnosis, and care coordination',
    legalBasis: 'medical_treatment',
    dpiaRequired: true,
    dpiaId: 'dpia-001',
    dpiaStatus: 'completed',
    safeguards: 'Role-based access control, AES-256 encryption, audit logging, network segmentation',
    accessControls: 'Treating physicians only, nurse read-only for assigned wards, no admin access to clinical data',
    encryptionApplied: true,
    pseudonymizationApplied: false,
    estimatedRecords: 45000,
    status: 'active',
    reviewDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sdr-002',
    organizationId: 'org-001',
    dataType: 'biometric',
    dataTypeDescription: 'Fingerprint templates for staff attendance system',
    processingPurpose: 'Employee attendance tracking and physical access control',
    legalBasis: 'explicit_consent',
    dpiaRequired: true,
    dpiaId: 'dpia-002',
    dpiaStatus: 'in_progress',
    safeguards: 'Hashed biometric templates only, separate isolated server, no network access',
    accessControls: 'HR system only, DPO oversight required for any export',
    encryptionApplied: true,
    pseudonymizationApplied: true,
    estimatedRecords: 1200,
    status: 'active',
    reviewDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sdr-003',
    organizationId: 'org-001',
    dataType: 'financial',
    dataTypeDescription: 'Patient billing information, insurance details, and payment records',
    processingPurpose: 'Healthcare billing, insurance claims processing, and financial reporting',
    legalBasis: 'legal_obligation',
    dpiaRequired: true,
    dpiaStatus: 'not_started',
    safeguards: 'PCI-DSS compliant payment processor, tokenized card data',
    accessControls: 'Finance team only, external auditor access requires DPO approval',
    encryptionApplied: true,
    pseudonymizationApplied: false,
    estimatedRecords: 28000,
    status: 'active',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sdr-004',
    organizationId: 'org-001',
    dataType: 'minor_data',
    dataTypeDescription: 'Pediatric patient records for children under 18',
    processingPurpose: 'Pediatric medical care and treatment',
    legalBasis: 'medical_treatment',
    dpiaRequired: true,
    dpiaStatus: 'not_started',
    safeguards: 'Parental consent required, enhanced access restrictions, no data sharing without guardian approval',
    accessControls: 'Pediatric department only, parental access via secure portal',
    encryptionApplied: true,
    pseudonymizationApplied: true,
    estimatedRecords: 6200,
    status: 'active',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Audit Logs ───────────────────────────────────────────────────────────────
export const DEMO_AUDIT_LOGS = [
  { id: 'log-001', actorRole: 'user', action: 'CONSENT_APPROVED', resourceType: 'ConsentRequest', resourceId: 'req-001', description: 'User approved Health Records Access consent', ipAddress: '10.0.1.42', severity: 'info', createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
  { id: 'log-002', actorRole: 'user', action: 'CONSENT_REJECTED', resourceType: 'ConsentRequest', resourceId: 'req-003', description: 'User rejected Behavioral Analytics consent', ipAddress: '10.0.1.55', severity: 'info', createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString() },
  { id: 'log-003', actorRole: 'org_admin', action: 'ADMIN_LOGIN', resourceType: 'User', description: 'Admin logged in from Riyadh', ipAddress: '10.0.2.10', severity: 'info', createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString() },
  { id: 'log-004', actorRole: 'org_admin', action: 'CONSENT_REQUEST_CREATED', resourceType: 'ConsentRequest', resourceId: 'req-001', description: 'Created new consent request: Health Records Access', ipAddress: '10.0.2.10', severity: 'info', createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'log-005', actorRole: 'user', action: 'OTP_REQUESTED', resourceType: 'User', description: 'OTP requested for authentication', ipAddress: '10.0.1.88', severity: 'info', createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'log-006', actorRole: 'user', action: 'CONSENT_WITHDRAWN', resourceType: 'ConsentRequest', description: 'User withdrew consent for Shopping Preferences', ipAddress: '10.0.1.42', severity: 'warning', createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'log-007', actorRole: 'user', action: 'ADMIN_LOGIN_FAILED', resourceType: 'User', description: 'Failed admin login attempt', ipAddress: '203.0.113.55', severity: 'critical', createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'log-008', actorRole: 'org_admin', action: 'CONSENT_REQUEST_UPDATED', resourceType: 'ConsentRequest', resourceId: 'req-005', description: 'Deactivated Telemedicine Data Processing request', ipAddress: '10.0.2.10', severity: 'warning', createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
];

// ─── Disclosure Records ────────────────────────────────────────────────────────
export const DEMO_DISCLOSURE_RECORDS = [
  {
    id: 'disc-001',
    organizationId: 'org-001',
    disclosingEntity: 'Ministry of Health',
    receivingEntity: 'National Health Insurance',
    receivingEntityType: 'government',
    purpose: 'Insurance claims processing and benefit verification',
    purposeCategory: 'service_delivery',
    dataCategories: ['health', 'pii'],
    dataFields: ['patient_id', 'diagnosis_code', 'treatment_date', 'insurance_number'],
    legalBasis: 'legal_obligation',
    art16ClearanceResult: 'approved',
    art16Violations: [],
    policyDecision: { allowed: true, decision: 'APPROVED' },
    isCrossBorder: false,
    status: 'active',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'disc-002',
    organizationId: 'org-001',
    disclosingEntity: 'Ministry of Health',
    receivingEntity: 'International Medical Research Institute',
    receivingEntityType: 'organization',
    purpose: 'Epidemiological research on chronic disease prevalence',
    purposeCategory: 'research',
    dataCategories: ['health', 'biometric'],
    dataFields: ['age_group', 'diagnosis', 'biometric_markers', 'genetic_data'],
    legalBasis: 'consent',
    art16ClearanceResult: 'blocked',
    art16Violations: [
      { ruleId: 'ART16-001', reason: 'Sensitive health and genetic data requires explicit consent — legal basis "consent" insufficient without explicit form', severity: 'critical' },
      { ruleId: 'ART16-005', reason: 'Cross-border transfer to non-adequate country requires approved safeguards', severity: 'critical' },
    ],
    isCrossBorder: true,
    destinationCountry: 'United States',
    transferSafeguards: null,
    status: 'pending',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'disc-003',
    organizationId: 'org-001',
    disclosingEntity: 'Ministry of Health',
    receivingEntity: 'Regional Hospital Network',
    receivingEntityType: 'organization',
    purpose: 'Coordinated patient care and treatment continuity',
    purposeCategory: 'service_delivery',
    dataCategories: ['health', 'pii'],
    dataFields: ['patient_name', 'medical_history', 'current_medications', 'allergies'],
    legalBasis: 'vital_interests',
    art16ClearanceResult: 'approved',
    art16Violations: [],
    isCrossBorder: false,
    status: 'executed',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Destruction Certificates ─────────────────────────────────────────────────
export const DEMO_DESTRUCTION_CERTIFICATES = [
  {
    id: 'cert-001',
    organizationId: 'org-001',
    certificateNumber: 'DEST-2025-000001',
    dataCategory: 'pii',
    dataDescription: 'Patient registration records older than 7 years — automated retention enforcement',
    recordCount: 15420,
    destructionMethod: 'deletion',
    destructionScope: 'patient_registry table (primary DB + all backup replicas)',
    destructedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    destructionTrigger: 'retention_expiry',
    verificationHash: 'a3f8c2d91e4b567890abcdef1234567890abcdef1234567890abcdef12345678',
    verifiedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    legalBasisForDestruction: 'PDPL Art. 18 — 7-year retention period exceeded',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cert-002',
    organizationId: 'org-001',
    certificateNumber: 'DEST-2025-000002',
    dataCategory: 'health',
    dataDescription: 'Anonymization of behavioral health screening data per DSAR deletion request — Case PDPL-2025-00142',
    recordCount: 1,
    destructionMethod: 'anonymization',
    destructionScope: 'health_screenings table — specific patient record anonymized',
    destructedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    destructionTrigger: 'dsar_deletion',
    verificationHash: 'b7e2a9f3d580123456abcdef9876543210fedcba9876543210fedcba98765432',
    verifiedAt: null,
    legalBasisForDestruction: 'PDPL Art. 4 — Data subject deletion request fulfilled',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
